name: llm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - langchain
  - openai
  - notebook
  - python-dotenv
  - pandas
  - pypdf
  - tiktoken

post-link:
  - conda config --set channel_priority strict